name: cypress-adv

on:
  push:
    branches:
      - 04-e2e-testing
  pull_request:

jobs:
  # eslint:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install modules
  #       run: npm install
  #     - name: Run ESLint
  #       run: npm run lint
  cypress-tests-desktop:
    # needs: eslint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run end-to-end tests on desktop viewport 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
          CYPRESS_MAILOSAUR_SERVER_ID: ${{ secrets.CYPRESS_MAILOSAUR_SERVER_ID }}
          CYPRESS_MAILOSAUR_API_KEY: ${{ secrets.CYPRESS_MAILOSAUR_API_KEY }}
          CYPRESS_CREDIT_CARD_HOLDER: ${{ secrets.CYPRESS_CREDIT_CARD_HOLDER }}
          CYPRESS_CREDIT_CARD_NUMBER: ${{ secrets.CYPRESS_CREDIT_CARD_NUMBER }}
          CYPRESS_CREDIT_CARD_CVC: ${{ secrets.CYPRESS_CREDIT_CARD_CVC }}
          CYPRESS_CREDIT_CARD_EXP_DATE: ${{ secrets.CYPRESS_CREDIT_CARD_EXP_DATE }}
          CYPRESS_CREDIT_CARD_POSTAL_CODE: ${{ secrets.CYPRESS_CREDIT_CARD_POSTAL_CODE }}
        with:
          command: npm test
  cypress-tests-tablet:
    # needs: eslint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run end-to-end tests on tablet viewport 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}
        with:
          command: npm run test:tablet
